## Pandas로 데이터 가공하기

NumPy를 활용하여 복잡한 데이터 배열(n 차원)을 저장하고 가공할 수 있었다. Pandas는 NumPy를 기반으로 만들어진 새로운 패키지로서 DataFrame이라는 효율적인 자료구조를 제공한다. 
- DataFrame : 근본적으로 행과 열 레이블이 부착된 다차원 배열, 여러가지 타입의 데이터를 저장할 수 있으며 데이터 누락도 혀용, **데이터베이스와 스프레드시트 프로그램과 유사**

### Pandas 설치 및 사용

시스템에 Pandas를 설치하려면 먼저 Numpy가 설치되어 있어야한다. 일반적으로 Numpy를 np라는 별명으로 임포트 하는 것처럼 Pandas도 pd라는 별명으로 임포트

In [4]:
import pandas as pd

### Pandas 객체 소개

Pandas는 기본 자료구조(Series, DataFrame, Index)에 추가로 여러 유용한 도구와 메서드, 기능을 제공하지만 먼저 기본 자료구조에 대해 알아보자 

#### Pandas Series 객체

Pandas Series는 인덱싱된 데이터의 1차원 배열, 리스트나 배열로 부터 만들 수 있다.

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Series는 값과 인덱스 속성으로 접근할 수 있다.

In [6]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

Numpy 배열과 마찬가지로 데이터는 친숙한 괄호 표기법으로 인덱스 접근 가능

In [8]:
data[1]

0.5

In [9]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### Series : 일반화된 Numpy 배열

Numpy 배열에는 값에 접근하는데 사용되는 암묵적 정수형 인덱스(0,1,2,3,...)가 있고, Pandas Series에는 값에 명시적으로 연결된 인덱스가 있음

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
data['b']

0.5

인접하지 않거나 연속적이지 않은 인덱스 사용 가능

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2,5,3,7])
data[5]

0.5

#### Series : 딕셔너리 활용

딕셔너리를 활용하여 Pandas Series 객체를 구성함으로써 의미를 분명하게 정할 수 있다

In [13]:
pop_dict = {'California' : 38332521, 'Texas' : 19552862, 'New York' : 128832123, 
            'Florida' : 195321122, 'illinois' : 2582123 }
pop = pd.Series(pop_dict)
pop

California     38332521
Florida       195321122
New York      128832123
Texas          19552862
illinois        2582123
dtype: int64

In [14]:
pop['California']

38332521

In [15]:
pop['California' : 'New York']

California     38332521
Florida       195321122
New York      128832123
dtype: int64

##### Quiz
다음 데이터로 시리즈 객체 만들기
area_dic = {'California' : 423967, 'Texas' : 695662, 'New York' : 141297, 
            'Florida' : 170312, 'illinois' : 149995 } 

### Pandas DataFrame 객체

#### DataFrame : 일반회된 Numpy 배열

Series가 유연한 인덱스를 가지는 1차원 배열이면 DataFrame은 유연한 행 인덱스와 열이름을 가진 2차원 배열

In [16]:
area_dic = {'California' : 423967, 'Texas' : 695662, 'New York' : 141297, 
            'Florida' : 170312, 'illinois' : 149995 } 

In [17]:
area = pd.Series(area_dic)
area

California    423967
Florida       170312
New York      141297
Texas         695662
illinois      149995
dtype: int64

In [18]:
pop

California     38332521
Florida       195321122
New York      128832123
Texas          19552862
illinois        2582123
dtype: int64

pop Series와 area Series(1차원)을 합쳐 2차원 객체 구성

In [19]:
states = pd.DataFrame({'population':pop, 'area': area})
states

area  population
California  423967    38332521
Florida     170312   195321122
New York    141297   128832123
Texas       695662    19552862
illinois    149995     2582123

In [20]:
states.index

Index(['California', 'Florida', 'New York', 'Texas', 'illinois'], dtype='object')

In [21]:
states.columns

Index(['area', 'population'], dtype='object')

열 이름으로 Series 객체를 참조 

In [22]:
states['area']

California    423967
Florida       170312
New York      141297
Texas         695662
illinois      149995
Name: area, dtype: int64

#### DataFrame 객체 구성하기

In [23]:
pd.DataFrame(pop, columns=['population'])

population
California    38332521
Florida      195321122
New York     128832123
Texas         19552862
illinois       2582123

In [24]:
data = [{'a':i, 'b':2*i} for i in range(3) ]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [25]:
pd.DataFrame([{'a':1, 'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [26]:
data = pd.DataFrame({'population' : pop, 'area' : area})
data

area  population
California  423967    38332521
Florida     170312   195321122
New York    141297   128832123
Texas       695662    19552862
illinois    149995     2582123

In [27]:
import numpy as np

pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.843734  0.266392
b  0.853321  0.957828
c  0.213238  0.052945

In [28]:
data['density'] = data['population'] / data['area']
data

area  population      density
California  423967    38332521    90.413926
Florida     170312   195321122  1146.842982
New York    141297   128832123   911.782437
Texas       695662    19552862    28.106842
illinois    149995     2582123    17.214727

##### Quiz
다음 데이터(pd_data01.xlsx)로 데이터프레임 객체를 만드세요.

In [29]:
def myfunc(a):
    return a * 10

data['multi_1'] = myfunc(data['area'])
#data['multi_2'] = (lambda a : a * 10)(data['area'])

In [30]:
# data = data.drop('multi_1', axis=1)
# data = data.drop('Texas')

In [31]:
data

area  population      density  multi_1
California  423967    38332521    90.413926  4239670
Florida     170312   195321122  1146.842982  1703120
New York    141297   128832123   911.782437  1412970
Texas       695662    19552862    28.106842  6956620
illinois    149995     2582123    17.214727  1499950

##### Quiz
앞에서 만든 데이터프레임 객체 '행사진행일수' 칼럼을 만드세요.

### Pandas Index 객체

Series와 DataFrame 객체에서 데이터를 참조하고 수정하게 해주는 Index객체는 배열 처럼 관련함수 사용 가능, 단 **객체처럼 변경 불가**

In [32]:
ind = pd.Index([2,3,5,7,11])

In [33]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [34]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [35]:
# ind[1] = 0

#### 인덱서 : loc, iloc

Series 혹은 DataFrame 객체가 명시적인 정수 인덱스를 가지고 있다면, 인덱싱 혹은 슬라이싱 할때 혼선이 발생

In [36]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [37]:
data[1] # 직접 정수 인덱스 사용

'a'

In [38]:
data[1:3] # 파이썬에서 정해진 인덱스 (0,1,2) 사용

3    b
5    c
dtype: object

Pandas는 특정 인덱싱 방식만 활용할 수 있는 인덱서(indexer) 속성을 제공

- loc 인덱서는 직접 정한 인덱스만 사용한다

In [39]:
data.loc[1]

'a'

In [40]:
data.loc[1:3]

1    a
3    b
dtype: object

- iloc 인덱서는 파이썬 내부에서 정한 인덱스만 활용한다.

In [41]:
data.iloc[1]

'b'

In [42]:
data.iloc[1:3]

3    b
5    c
dtype: object

### Pandas에서 데이터 연산하기

numpy로 기본 산술 연산, 삼각함수, 지수, 로그함수 등 요소 단위의 연산을 빠르게 수행할 수 있다. Pandas는 Numpy로 부터 이 기능을 대부분 상속
- 단항 연산의 경우, 유니버설 함수가 결과물에 인덱스와 열 테이블을 보존 (유니버설 함수: 배열 안에 있는 데이터 원소 별로 연산을 수행하는 함수)
- 이항 연산의 경우, Pandas가 유니버설 함수에 객체를 전달할 때 인덱스를 자동으로 정렬

#### 인덱스 보존

In [43]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4)) # 0에서 10까지 4개
ser

0    6
1    3
2    7
3    4
dtype: int64

In [44]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns=['A','B','C','D'])

In [45]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [46]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [47]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

#### 인덱스 정렬

두개의 Series 또는 DataFrame객체에 이항 연산을 적용하는 경우 Pandas는 연산을 수행하는 과정에서 인덱스를 정렬

In [48]:
area = pd.Series({'Alaska': 1722321, 'Texas':394842, 'California':397393},
                 name='area')
population = pd.Series({'California':39283912, 'Texas':39481293, 'New York': 39581232},
                       name='population')

In [49]:
population / area

Alaska              NaN
California    98.854061
New York            NaN
Texas         99.992638
dtype: float64

In [50]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])

In [51]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

누락된 요소에 채우기 값을 선택해 명시적으로 지정

In [52]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [53]:
A = pd.DataFrame(rng.randint(0,20,(2,2)), columns=list('AB'))

In [54]:
A

A   B
0  1  11
1  5   1

In [55]:
B = pd.DataFrame(rng.randint(0,10,(3,3)), columns=list('BAC'))

In [56]:
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [57]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [58]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

파이썬 연산자와 Pandas 메서드 매핑

| 파이썬 연산자 |       Pandas 메서드        |
| :-----------: | :------------------------: |
|       +       |           add()            |
|       -       |     sub(), subtract()      |
|       *       |     mul(), multiply()      |
|       /       | div(), truediv(), divide() |
|      //       |         floordiv()         |
|       %       |           mod()            |
|      **       |           pow()            |

##### Quiz
다음과 같은 데이터 프레임을 만들고 두 좌표(left, top), (right, bottom)로 만들어지는 평면의 면적을 구하여 데이터 프레임의 빈 값을 체우세요

In [76]:
quiz = pd.read_csv('/Users/raejin/python-programming-class/quiz2.csv', index_col=0)
quiz

지역  left  top  right  bottom  평면
1  A     0    1      4       5 NaN
2  B     2    6      6       7 NaN
3  C     6    1      7       4 NaN
4  D     3    5      5       9 NaN

In [84]:
w = np.array(quiz['right'].values - quiz['left'].values)
h = np.array(quiz['bottom'].values - quiz['top'].values)

In [88]:
quiz['평면'] = w * h
quiz

지역  left  top  right  bottom  평면
1  A     0    1      4       5  16
2  B     2    6      6       7   4
3  C     6    1      7       4   3
4  D     3    5      5       9   8

### DataFrame과 Series 간의 연산

DataFrame과 Series 사이의 연산할 때 인덱스와 열의 순서는 비슷하게 유지

In [ ]:
A = rng.randint(10, size=(3,4))
A

In [ ]:
A - A[0]

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))

In [ ]:
df

In [ ]:
df-df.iloc[0]

DataFrame, Series 연산은 앞에서 언급했던 연산과 마찬가지로 두 요소간의 인덱스를 자동으로 맞춘다.

In [ ]:
halfrow = df.iloc[0, ::2]
halfrow

In [ ]:
df - halfrow

## 누락된 데이터 처리하기

누락된 데이터 존재를 나타내기 위한 여러 가지 방식
    - 1비트를 누락 전용 표기로 활용 (P0012, N0012, P0014, P0015 ...)
    - 데이터에서 나올 수 없는 값 (-1, -9999, 0101010)
    - NaN(Not a Number)로 표시
    - NA(Nat Available) : 값이 결손(손상)됨, Pandas에 미포함
    - Null : 값이 존재하지 않는다. 손상되어 쓸 수 없는 경우도 포함

### None : 파이썬의 누락된 데이터

None은 파이썬 코드에서 누락된 데이터 표시를 위해 사용, Pandas/Numpy 에서는 데이터 타입이 'object'일 경우에만 사용할 수 있다.

In [ ]:
import numpy as np
import pandas as pd

vals1 = np.array([1, 2, 3, 4])
vals1

In [ ]:
vals2 = np.array([1, None, 3, 4])
vals2

None 값을 가진 배열에서 sum()이나 min()같은 연산을 하면 오류가 발생

In [ ]:
vals1.sum()


In [ ]:
# vals2.sum()

### NaN : 누락된 숫자 데이터

NaN(Not a Number)는 표준 IEEE 부동소수점 표기를 사용하는 모든 시스템이 인식하는 **특수 부동 소수점 값**이다

In [ ]:
val2 = np.array([1, np.nan, 3, 4])
val2

In [ ]:
val2.dtype

NaN이 포함된 산술 연산의 결과는 항상 NaN

In [ ]:
1 + np.nan

In [ ]:
val2.sum()

NaN 값을 무시하는 연산들

In [ ]:
np.nansum(val2), np.nanmin(val2), np.nanmax(val2)

### Pandas에서 NaN과 None

NaN과 None은 각자의 역할이 있고 Pandas에서는 이 둘을 서로 호환 및 변환 할 수 있다.

In [ ]:
pd.Series([1, np.nan, 2, None])

In [ ]:
x = pd.Series(range(2), dtype=int)
x

In [ ]:
x[0] = None
x

### 널 값 연산하기

Pandas는 None과 NaN을 근본적으로 누락된 값이나 없는 값을 가리키기 위해 호환되는 값으로 처리한다. 데이터에서 이 값들을 감시하고 삭제하는데 유용한 메소드들이 있다ㅡ



#### 널 값 감지 isnull(), notnull()

널 데이터를 탐지하기 위한 메소드로 데이터에 대한 불 배열을 반환한다



In [ ]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

In [ ]:
data[data.notnull()]

#### 널 값 제거하기 dropna(), fillna()

NA값을 제거하는 dropna(), NA값을 채우는 fillna()

In [ ]:
data.dropna()

In [ ]:
df = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, 4, 6]])
df

dropna()는 데이터프레임에 대해 널 값이 있는 모든 행을 삭제한다.

In [ ]:
df.dropna()

In [ ]:
df.dropna(axis='rows') # 행일 경우 rows

In [ ]:
df

In [ ]:
df[3] = np.nan

In [ ]:
df

In [ ]:
행이나 열의 값이 모두 NA값이거나 일부분만 NA일 경우 how, thresh 제거할 기준을 조정한다.
기본 how값은 any : NA값이 있는 행이나 열을 모두 제거

In [ ]:
df.dropna(axis='columns', how='all')

thresh 옵션은 행이나 열에서 널이 아닌 값이 최소 몇 개 있는지 지정

In [ ]:
df.dropna(axis='rows', thresh=3)

#### 널 값 채우기 fillna()

NA 값을 삭제하지 않고 유효한 값으로 대체해야 할 때가 있다. Pandas는 이러한 연산을 위해 fillna()함수를 제공한다.

In [ ]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))

In [ ]:
data

In [ ]:
data.fillna(0)

이전 값으로 체우는 ffill(forward-fill), bfill(back-fill)과 기준 축 지정 axis(rows는 0 columns은 1)

In [ ]:
data.fillna(method='ffill')

In [ ]:
data.fillna(method='bfill')

In [ ]:
df

In [ ]:
df.fillna(method='ffill', axis=1) 

## 데이터 프레임을 csv 파일로 내보내기, 읽어오기

### 내보내기

데이터프레임에서 to_csv("파일이름.csv") 함수로 작성한 내용을 csv 파일로 저장할 수 있다.
파일이름을 입력할 때 확장명(.csv)를 생략하지 않는다.

In [ ]:
df = pd.DataFrame(rng.randint(0,20,(2,2)), columns=list('AB'))

In [ ]:
df.to_csv('export.csv')

### 읽어오기

csv 파일에서 저장한 데이터를 데이터프레임으로 읽어오려면 read_csv('파일경로\파일이름.csv', index_col=0)함수를 활용, (index_col = 0은 0번째 행을 인덱스로 활용한다는 의미)

In [ ]:
df_read = pd.read_csv('/Users/raejin/python-programming-class/export.csv', index_col=0)
print(df_read.head()) 

##### Quiz
다음과 같이 데이터가 있을 때 데이터프레임을 만들고 아래와 같이 누락된 데이터를 처리하세요.

In [ ]:
state = pd.Series(['AK', 'AL', 'CA', 'FL', 'HI','IA'])
state

In [ ]:
gender = pd.Series([np.nan, np.nan, 0, np.nan, 0, np.nan])
gender

In [ ]:
name = pd.Series(['Elsie',
'Clyde',
'Russell',
'Eliza',
'Charles',
'Margaret',])
name

In [ ]:
win = pd.Series([38,
38,
32,
32,
33,
25])
win

In [ ]:
lose = pd.Series([1,
np.nan,
np.nan,
np.nan,
np.nan,
np.nan])
lose

In [ ]:
quiz = pd.DataFrame({'state':state, 'gender':gender, 'name':name, 'win':win, 'lose':lose})

In [ ]:
quiz

In [ ]:
quiz = quiz[['state','gender','name','win','lose']]

In [ ]:
quiz

In [ ]:
quiz.to_csv('quiz1.csv')

In [ ]:
quiz_load = pd.read_csv('./quiz1.csv', index_col=0)
quiz_load

#### 풀이

In [ ]:
quiz2 = quiz.dropna(axis='rows', thresh=4)

In [ ]:
quiz2

In [ ]:
quiz3 = quiz.dropna(axis='columns')

In [ ]:
quiz3

## 계층적 인덱싱

Pandas는 고차원의 데이터를 처리하는 객체를 제공하지만 주로 단일 인덱스 내에 여러 인덱스 레벨을 포함하는 계층적 인덱싱(hierarchical indexing, 다중 인덱싱(multi-indexing))을 활용한다. 이 방식으로 고차원 데이터를 익숙한 1차원 Series와 2차원 DataFrame 객체로 간결하게 표현할 수 있다.

### 다중 인덱스된 Series

In [ ]:
pop = pd.DataFrame([{"2000" : 33871648, "2010" : 37253956}, 
                    {"2000" : 18976457, "2010" : 19378102},
                    {"2000" : 20851820, "2010" : 25145561}], 
                   index=['California', 'New York','Taxas'])

In [ ]:
pop

#### 튜플을 키로 사용

In [ ]:
index = [('California', 2000), ('California', 2001),
        ('New York', 2000), ('New York', 2001),
        ('Taxas', 2000), ('Taxas', 2001)]

In [ ]:
population = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [ ]:
pop2 = pd.Series(population, index=index)

In [ ]:
pop2

In [ ]:
pop2[[i for i in pop2.index if i[1] == 2000]]

#### Pandas MultiIndex

In [ ]:
index2 = pd.MultiIndex.from_tuples(index)
index2

In [ ]:
pop3 = pop2.reindex(index2) # 

In [ ]:
pop3

In [ ]:
pop3[:, 2001]

unstack() 함수는 다중 인덱스를 가진 Series를 전형적인 인덱스의 DataFrame으로 빠르게 변환해 준다. stack() 함수는 반대 연산을 제공한다.

In [ ]:
pop4 = pop3.unstack()
pop4

In [ ]:
pop5 = pop4.stack()
pop5

In [ ]:
pop_df = pd.DataFrame({'total': pop5,
                      'under18' : [9267089, 9284094,
                                  4687374, 4318033,
                                  5906301, 6879014]})
pop_df

In [ ]:
f_u18 = pop_df['under18'] / pop_df['total']


In [ ]:
f_u18

In [ ]:
f_u18.unstack()

In [ ]:
df = pd.DataFrame(np.random.rand(4,2),
                 index=[['a','a','b','b'],[1,2,1,2]],
                 columns=['data1','data2'])

In [ ]:
df

### 명시적 MultiIndex 생성자

In [ ]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]]) # 배열

In [ ]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)]) # 튜플

In [ ]:
pd.MultiIndex.from_product([['a','b'],[1,2]]) # 데카르트 곱

In [ ]:
pd.MultiIndex(levels=[['a','b'],[1,2]], labels=[[0,0,1,1],[0,1,0,1]]) # 직접 입력 생성

### MultiIndex 레벨 이름

MultiIndex의 레벨에 이름을 지정할 수 있다. MultiIndex 생성자에 names 인수를 전달하거나 생성 후에 인덱스의 names 속성을 성정해 이름을 지정 가능

In [ ]:
pop5.index.names = ['state','year']
pop5

### 열의 MultiIndex

In [89]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]], names=['year','visit'])

In [90]:
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']], 
                                     names=['subject', 'type'])

In [127]:
data = np.round(np.random.randn(4,6),1)

In [128]:
data

array([[ 0.2, -0.4,  1.3, -0.5, -0.1, -1.5],
       [-1.4, -2. , -0.3,  0.5,  0.8,  0.2],
       [-0.2,  0.1, -0.3, -1.2, -0.6, -0.5],
       [ 1.6, -1.3, -0.3,  0.2,  1. , -0.2]])

In [129]:
data[:, ::2] *= 10

In [130]:
data += 37

In [131]:
data

array([[39. , 36.6, 50. , 36.5, 36. , 35.5],
       [23. , 35. , 34. , 37.5, 45. , 37.2],
       [35. , 37.1, 34. , 35.8, 31. , 36.5],
       [53. , 35.7, 34. , 37.2, 47. , 36.8]])

In [96]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [97]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      27.0  36.7  37.0  37.6  43.0  37.6
     2      39.0  37.9   7.0  37.3  37.0  36.5
2014 1      27.0  35.8  39.0  36.4  27.0  38.2
     2      44.0  38.5  32.0  37.8  49.0  34.4

In [98]:
health_data['Bob']

type          HR  Temp
year visit            
2013 1      27.0  36.7
     2      39.0  37.9
2014 1      27.0  35.8
     2      44.0  38.5

In [354]:
index = pd.MultiIndex.from_product([["Brown Stone", "North", "Central", "South"], ["Condominium","House"]], 
                                   names=['area','type'])

In [355]:
index

MultiIndex(levels=[['Brown Stone', 'Central', 'North', 'South'], ['Condominium', 'House']],
           labels=[[0, 0, 2, 2, 1, 1, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]],
           names=['area', 'type'])

In [356]:
law = np.absolute(np.round(np.random.randn(8, 4), 1))
law

#quiz = pd.DataFrame()

array([[1. , 1. , 1.4, 0.3],
       [0.6, 1.1, 0.6, 0.3],
       [1.2, 1.6, 0.6, 0.2],
       [0.6, 0.1, 0.6, 1.5],
       [2. , 0.4, 0.4, 0.1],
       [1.5, 0.4, 1.7, 0.3],
       [1.2, 0.5, 1.8, 1.5],
       [1.1, 1.4, 0.1, 0.7]])

In [357]:
law[:, 0] *= 1000
law[:, 1] *= 2000
law[:, 2] *= 3000
law[:, 3] *= 5000

law += 120
#law = np.absolute(law)

In [358]:
law

array([[1120., 2120., 4320., 1620.],
       [ 720., 2320., 1920., 1620.],
       [1320., 3320., 1920., 1120.],
       [ 720.,  320., 1920., 7620.],
       [2120.,  920., 1320.,  620.],
       [1620.,  920., 5220., 1620.],
       [1320., 1120., 5520., 7620.],
       [1220., 2920.,  420., 3620.]])

In [359]:
np.save('quiz3.npy', law)

In [360]:
law = np.load('./quiz3.npy')

In [361]:
law

array([[1120., 2120., 4320., 1620.],
       [ 720., 2320., 1920., 1620.],
       [1320., 3320., 1920., 1120.],
       [ 720.,  320., 1920., 7620.],
       [2120.,  920., 1320.,  620.],
       [1620.,  920., 5220., 1620.],
       [1320., 1120., 5520., 7620.],
       [1220., 2920.,  420., 3620.]])

In [362]:
columns = pd.MultiIndex.from_product([[2017, 2018],['전반기','후반기']], names=['year', 'Quarter'])


In [363]:
columns

MultiIndex(levels=[[2017, 2018], ['전반기', '후반기']],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['year', 'Quarter'])

In [364]:
index

MultiIndex(levels=[['Brown Stone', 'Central', 'North', 'South'], ['Condominium', 'House']],
           labels=[[0, 0, 2, 2, 1, 1, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]],
           names=['area', 'type'])

In [365]:
estate = pd.DataFrame(law, index=index, columns=columns)

##### MultiIndex를 활용하여 다음과 같은 데이터프레임을 만드세요(원천 데이터는 Quiz3.npy 제공)

In [366]:
estate

year                       2017            2018        
Quarter                     전반기     후반기     전반기     후반기
area        type                                       
Brown Stone Condominium  1120.0  2120.0  4320.0  1620.0
            House         720.0  2320.0  1920.0  1620.0
North       Condominium  1320.0  3320.0  1920.0  1120.0
            House         720.0   320.0  1920.0  7620.0
Central     Condominium  2120.0   920.0  1320.0   620.0
            House        1620.0   920.0  5220.0  1620.0
South       Condominium  1320.0  1120.0  5520.0  7620.0
            House        1220.0  2920.0   420.0  3620.0

In [367]:
estate[2017, '전반기']

area         type       
Brown Stone  Condominium    1120.0
             House           720.0
North        Condominium    1320.0
             House           720.0
Central      Condominium    2120.0
             House          1620.0
South        Condominium    1320.0
             House          1220.0
Name: (2017, 전반기), dtype: float64

#### 배열 슬라이싱

numpy의 슬라이싱은 표준 파이썬 구문에 따르지만, 시작인덱스에서 마지막 인덱스까지 일정 간격을 두어 띄여서 값을 슬라이스 할 수 있다.

배열이름[시작인덱스:마지막인덱스:간격]

시작인덱스, 마지막 인덱스, 간격을 설정하지 않으면 기본적으로는 0, 데이터 갯수, 1로 설정된다.

In [368]:
estate[0:7:2]

year                       2017            2018        
Quarter                     전반기     후반기     전반기     후반기
area        type                                       
Brown Stone Condominium  1120.0  2120.0  4320.0  1620.0
North       Condominium  1320.0  3320.0  1920.0  1120.0
Central     Condominium  2120.0   920.0  1320.0   620.0
South       Condominium  1320.0  1120.0  5520.0  7620.0

In [369]:
estate.iloc[:5, :3]

year                       2017            2018
Quarter                     전반기     후반기     전반기
area        type                               
Brown Stone Condominium  1120.0  2120.0  4320.0
            House         720.0  2320.0  1920.0
North       Condominium  1320.0  3320.0  1920.0
            House         720.0   320.0  1920.0
Central     Condominium  2120.0   920.0  1320.0

In [370]:
estate.loc[:,(2017, '전반기')]

area         type       
Brown Stone  Condominium    1120.0
             House           720.0
North        Condominium    1320.0
             House           720.0
Central      Condominium    2120.0
             House          1620.0
South        Condominium    1320.0
             House          1220.0
Name: (2017, 전반기), dtype: float64

In [371]:
idx = pd.IndexSlice
estate.loc[idx[:, 'Condominium'], idx[:, '전반기']]

year                       2017    2018
Quarter                     전반기     전반기
area        type                       
Brown Stone Condominium  1120.0  4320.0
North       Condominium  1320.0  1920.0
Central     Condominium  2120.0  1320.0
South       Condominium  1320.0  5520.0

##### Quiz 
다음의 estate 데이터 프레임을 다음과 같이 슬라이스 하시오

In [372]:
estate

year                       2017            2018        
Quarter                     전반기     후반기     전반기     후반기
area        type                                       
Brown Stone Condominium  1120.0  2120.0  4320.0  1620.0
            House         720.0  2320.0  1920.0  1620.0
North       Condominium  1320.0  3320.0  1920.0  1120.0
            House         720.0   320.0  1920.0  7620.0
Central     Condominium  2120.0   920.0  1320.0   620.0
            House        1620.0   920.0  5220.0  1620.0
South       Condominium  1320.0  1120.0  5520.0  7620.0
            House        1220.0  2920.0   420.0  3620.0

In [373]:
idx = pd.IndexSlice
estate.loc[idx[:, 'House'], idx[2018, :]]

year                 2018        
Quarter               전반기     후반기
area        type                 
Brown Stone House  1920.0  1620.0
North       House  1920.0  7620.0
Central     House  5220.0  1620.0
South       House   420.0  3620.0

In [374]:
estate.iloc[1:8:2, 2:4:1]

year                 2018        
Quarter               전반기     후반기
area        type                 
Brown Stone House  1920.0  1620.0
North       House  1920.0  7620.0
Central     House  5220.0  1620.0
South       House   420.0  3620.0

### 다중 인덱스 재정렬하기

#### 정렬된 인덱스와 정렬되지 않은 인덱스

In [375]:
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])

In [376]:
data = pd.Series(np.random.rand(6), index=index)

In [377]:
data.index.names = ['char','int']

In [378]:
data

char  int
a     1      0.973548
      2      0.843034
c     1      0.789752
      2      0.133736
b     1      0.801040
      2      0.166435
dtype: float64

In [379]:
try:
    data['a':'b']
except Exception as e:
    print(e)

'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [380]:
data = data.sort_index()

In [381]:
data

char  int
a     1      0.973548
      2      0.843034
b     1      0.801040
      2      0.166435
c     1      0.789752
      2      0.133736
dtype: float64

In [382]:
data['a':'b']

char  int
a     1      0.973548
      2      0.843034
b     1      0.801040
      2      0.166435
dtype: float64

In [383]:
pop

0
state      year          
California 2000  33871648
           2010  37253956
New York   2000  18976457
           2010  19378192
Texas      2000  20851820
           2010  25145561

#### 인덱스 설정 및 재설정

In [384]:
index = pd.MultiIndex.from_product([['California','New York','Texas'],[2000,2010]], names=["state","year"])

In [385]:
pop = pd.DataFrame([33871648,37253956,18976457,19378192,20851820,25145561], index=index)

In [386]:
pop

0
state      year          
California 2000  33871648
           2010  37253956
New York   2000  18976457
           2010  19378192
Texas      2000  20851820
           2010  25145561

MultiIndex를 데이터프레임의 열로 만드는 reset_index()

In [387]:
pop_flat = pop.reset_index()
pop_flat

state  year         0
0  California  2000  33871648
1  California  2010  37253956
2    New York  2000  18976457
3    New York  2010  19378192
4       Texas  2000  20851820
5       Texas  2010  25145561

열값으로 MultiIndex를 만드는 set_index()

In [388]:
pop_flat.set_index(['state','year'])

0
state      year          
California 2000  33871648
           2010  37253956
New York   2000  18976457
           2010  19378192
Texas      2000  20851820
           2010  25145561

### 다중 인덱스에서 데이터 집계

다중인덱스가 적용되어 있는 데이터테이블도 mean(), sum(), max() 같은 집계 메소드를 활용할 수 있다. 원하는 열이나 행을 level 매개변수로 전달

In [403]:
estate

year                       2017            2018        
Quarter                     전반기     후반기     전반기     후반기
area        type                                       
Brown Stone Condominium  1120.0  2120.0  4320.0  1620.0
            House         720.0  2320.0  1920.0  1620.0
North       Condominium  1320.0  3320.0  1920.0  1120.0
            House         720.0   320.0  1920.0  7620.0
Central     Condominium  2120.0   920.0  1320.0   620.0
            House        1620.0   920.0  5220.0  1620.0
South       Condominium  1320.0  1120.0  5520.0  7620.0
            House        1220.0  2920.0   420.0  3620.0

In [404]:
data_mean = estate.mean(level='type')

In [405]:
data_mean

year           2017            2018        
Quarter         전반기     후반기     전반기     후반기
type                                       
Condominium  1470.0  1870.0  3270.0  2745.0
House        1070.0  1620.0  2370.0  3620.0

In [396]:
data_sum = estate.sum(axis=1, level='Quarter')

In [397]:
data_sum

Quarter                     전반기     후반기
area        type                       
Brown Stone Condominium  5440.0  3740.0
            House        2640.0  3940.0
North       Condominium  3240.0  4440.0
            House        2640.0  7940.0
Central     Condominium  3440.0  1540.0
            House        6840.0  2540.0
South       Condominium  6840.0  8740.0
            House        1640.0  6540.0

In [398]:
estate

year                       2017            2018        
Quarter                     전반기     후반기     전반기     후반기
area        type                                       
Brown Stone Condominium  1120.0  2120.0  4320.0  1620.0
            House         720.0  2320.0  1920.0  1620.0
North       Condominium  1320.0  3320.0  1920.0  1120.0
            House         720.0   320.0  1920.0  7620.0
Central     Condominium  2120.0   920.0  1320.0   620.0
            House        1620.0   920.0  5220.0  1620.0
South       Condominium  1320.0  1120.0  5520.0  7620.0
            House        1220.0  2920.0   420.0  3620.0